#
# Win32 makefile
#

CC:=gcc
CXX:=g++
PREFIX=../win32/
SUFFIX=.exe
LIBS=-lmingw32 -lSDLmain -lSDL.dll -mwindows -static-libstdc++ -static-libgcc -static
RM=	-del
EXTRA_OBJ=goaticon.o

include makefile.common
